### ISSUE TITLE
Invalid as plugin... 

### ISSUE THREAD

**Issue by carltongibson** [tailwindcss/typography#1]
Hi. 

I know this is _not ready for use_ but it doesn't appear to be a valid Tailwind plugin as it is... — I had to import it and then use it like so: 

```javascript
// tailwind.config.js
typography = require(...)

module.exports = {
  theme: {
    extend: typography.config.theme
  },
  variants: {},
  plugins: [
    typography.handler
  ]
}
```

I couldn't for the life of me see how that was magic'd together from the current state of the repo, but, I guess, a couple of paragraphs in the README showing how to wire it up might save a few folks a cycle. 

Anyhow, it's a great example, thanks!

**Comment by adamwathan** [comment]
This new format will work automatically in Tailwind 1.2, just not released yet 👍 

https://github.com/tailwindcss/tailwindcss/pull/1162

**Comment by carltongibson** [comment]
OK. Good to know. Thanks for the link. Will close. 🧐

**Comment by brandonpittman** [comment]
@adamwathan Speaking of 1.2, is there an ETA on the final release. I've got some plugins that are using the @next release.
