### ISSUE TITLE
Available through CDN?

### ISSUE THREAD

**Issue by mikebronner** [tailwindcss/typography#10]
Hi Adam, this looks absolutely amazing! Normally I wouldn't even ask about CDN availability, if it weren't for a site I manage that runs on a CMS that I don't control. 

Any chance this cold be released on a CDN and included in the header like TailwindCSS?

If not, I could probably make a build, upload it to GitHub, and link to that in my header.

Thanks for all that you do!
~Mike

**Comment by adamwathan** [comment]
Hey Mike! Yep you can actually pull it in via CDN already, here's the URL:

https://unpkg.com/@tailwindcss/typography@0.1.2/dist/typography.min.css

I'd recommend using it like this if you are using the rest of Tailwind via CDN as well:

```html
<link rel="stylesheet" href="https://unpkg.com/tailwindcss@1.4.6/dist/base.min.css">
<link rel="stylesheet" href="https://unpkg.com/tailwindcss@1.4.6/dist/components.min.css">
<link rel="stylesheet" href="https://unpkg.com/@tailwindcss/typography@0.1.2/dist/typography.min.css">
<link rel="stylesheet" href="https://unpkg.com/tailwindcss@1.4.6/dist/utilities.min.css">
```

**Comment by mikebronner** [comment]
Thanks Adam!

**Comment by thallada** [comment]
This is 404ing. What is the URL for 0.5.X versions?
```
<link rel="stylesheet" href="https://unpkg.com/@tailwindcss/typography@0.5.10/dist/typography.min.css">
```

**Comment by blowsie** [comment]
Im using this is sandbooxes
`<script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp,container-queries"></script>`
