### ISSUE TITLE
The styles for `pre` and `code` don't respect the font-family defined in the Tailwind configuration file

### ISSUE THREAD

**Issue by alihassan1133** [tailwindcss/typography#11]
![image](https://user-images.githubusercontent.com/62854082/87367721-c5339d00-c549-11ea-9835-98d1edd149b6.png)
![image](https://user-images.githubusercontent.com/62854082/87367742-d2508c00-c549-11ea-9070-2e980e4db5e7.png)

**Comment by alihassan1133** [comment]
And yes, I have the font pulled in from the CDN.

**Comment by adamwathan** [comment]
Will be fixed in the next release thanks to @ahaseeb04 🙌
