### ISSUE TITLE
Allow renaming of `prose`  PR?

### ISSUE THREAD

**Issue by OwenMelbz** [tailwindcss/typography#16]
Would you accept a PR that allows the user to define a custom base class name? Some might be restricted to certain ones based of CMSs such as `.wysiwyg` or `.cms-content` etc

e.g. something like..

```js
// tailwind.config.js
module.exports = {
  theme: {
    typography: {
        className: 'custom-class'
    }
  },
  plugins: [
    require('@tailwindcss/typography'),
    // ...
  ],
}
```

**Comment by adamwathan** [comment]
Yep I'd be open to this, but I'd rather configure it as a plugin option than a theme option:

```js
// tailwind.config.js
module.exports = {
  theme: {},
  plugins: [
    require('@tailwindcss/typography')({
      className: 'wysiwyg',
    }),
    // ...
  ],
}
```

**Comment by sjclark** [comment]
Was the syntax above what actually ended up being merged?
I'm using:
```
  plugins: [
    require('@tailwindcss/custom-forms'),
    require('@tailwindcss/typography')({
      className: 'test',
    }),
```
But it only ever seems to output/format under `prose`.

**Comment by pierreberchtold** [comment]
@sjclark  the change is in the master branch but it does not have been release yet. @adamwathan when do you plan the next release?

**Comment by adamwathan** [comment]
It should work in the latest release, just haven't written release notes yet sorry.
