### ISSUE TITLE
Can the prose classes be loaded from a CDN?

### ISSUE THREAD

**Issue by elimintz** [tailwindcss/typography#19]
I understand that the recommended use is installation using npm. My specific use is in developing the Python framework [JustPy](https://justpy.io) that uses tailwind and for which installation from npm is not possible.

Any suggestion would be appreciated.

**Comment by adamwathan** [comment]
Duplicate of https://github.com/tailwindcss/typography/issues/10

**Comment by elimintz** [comment]
Thank you!

**Comment by HugoDF** [comment]
@adamwathan would you be interested in a PR to add the CDN instructions in the README?

**Comment by adamwathan** [comment]
Definitely!
