### ISSUE TITLE
List followed by heading has the wrong margin

### ISSUE THREAD

**Issue by benface** [tailwindcss/typography#2]
A list (`ul` or `ol`) followed by a heading (`h2`, `h3`, or `h4`) has the wrong margin due to `.rich-text ul + *` overriding `.rich-text * + h2` (or `+ h3` or `+ h4`).

Moving the whole
```
'ol + *': {
  marginTop: defaultTheme.spacing[4],
},
```
and
```
'ul + *': {
  marginTop: defaultTheme.spacing[4],
},
```
blocks to the top should fix it.

**Comment by hugmanrique** [comment]
Same thing occurs with `pre` followed by a heading.

**Comment by adamwathan** [comment]
Thinking this is probably no longer an issue since redesigning and rewriting the whole plugin this month 😅  Let me know if you catch any new stuff though!
