### ISSUE TITLE
Footnotes have doubled numbers

### ISSUE THREAD

**Issue by brycewray** [tailwindcss/typography#23]
Thanks, TWCSS team! 🚀 👏 ✅  This looks really great, and the demo (especially when viewing the raw MDX file) is quite helpful. One thing the demo doesn't include is handling of Markdown/MDX footnotes. I briefly tried the plugin and saw that footnotes were generated with two sets of `ol`-style numbers... (e.g., and showing in a code block so GHMD won't render each second number as "i" or "ii")

```
1. 1. This is footnote 1.
2. 2. This is footnote 2.
```

...regardless of how I tried to mitigate this in my basic CSS all the way up to trying to kill all numbering. Suggestions? Fix in TWCSS 1.5.1? 😃

**Comment by adamwathan** [comment]
What’s the HTML that it generates for that?
GitHub <notifications@github.com> wrote:
“Thanks, TWCSS team! 🚀 👏 ✅ This looks really great, and the demo (especially when viewing the raw MDX file) is quite helpful. One thing the demo doesn't include is handling of Markdown/MDX footnotes. I briefly tried the plugin and saw that footnotes were generated with two sets of ol-style numbers... (e.g., and showing in a code block so GHMD won't render each second number as "i" or "ii")

1. 1. This is footnote 1.
2. 2. This is footnote 2.

...regardless of how I tried to mitigate this in my basic CSS all the way up to trying to kill all numbering. Suggestions? Fix in TWCSS 1.5.1? 😃”

**Comment by brycewray** [comment]
@adamwathan Disregard, sir. My problem. Forgot I had already used `@apply list-decimal` with my footnotes (which was the case with `ol` stuff in general; had similar issue with double bullets on `ul` until I commented out `@apply list-disc`). 🤷‍♂️
