### ISSUE TITLE
Specificity of utilities within prose

### ISSUE THREAD

**Issue by gizburdt** [tailwindcss/typography#27]
Hi, this plugin is really awesome! When I want a <p> within .prose to have .mb-0, it won't be set:

![Schermafbeelding 2020-07-16 om 14 58 57](https://user-images.githubusercontent.com/1470623/87673484-efb56e00-c774-11ea-8bd1-fc028e0a2a4f.png)

This is my tailwind.css (I use Nuxt):

```
@import 'tailwindcss/base';

@import 'tailwindcss/components';

@import 'tailwindcss/utilities';
```

Am I doing something wrong?

**Comment by adamwathan** [comment]
Just an unfortunate consequence of CSS specificity I'm afraid. See similar discussion here: https://github.com/tailwindcss/typography/issues/26

**Comment by gizburdt** [comment]
Thanks! Keep up the good work! :)
