### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by pspeter3** [tailwindcss/typography#3]
This plugin seems great for websites with markdown content! Is there anything I can do to help push it forward?

**Comment by adamwathan** [comment]
I'm actually working on it as we speak, hope to get a real release out in the next few weeks 👍

**Comment by pspeter3** [comment]
That's amazing! I'm looking forward to it!

**Comment by durkinio** [comment]
This will be a rather great complement to TailwindUI 💯

**Comment by menthol** [comment]
Is the light variant being considered?

**Comment by iksaku** [comment]
> Is light/dark variants being considered?

This would be pretty useful, however there are many ways in which developers could implement Dark mode... It may turn somehow difficult, unless there's a enable/disable property for the plugin, or a way for the plugin to rely on JS for Dark/Light mode.

**Comment by adamwathan** [comment]
Released 👍
