### ISSUE TITLE
Utility classes are not taking priority

### ISSUE THREAD

**Issue by jgile** [tailwindcss/typography#30]
This might just be user error.  I cannot get utility classes to take precedence over prose.  for example:

```html
<div class="prose">
    <h1 class="mb-0">Hello World</h1>
</div>
```
In this circumstance, the prose default margin is still used on the H1 tag.  CSS and tailwind.config.js:
css
```css
@tailwind base;
/* custom stuff */
@tailwind components;
/* custom stuff */
@tailwind utilities;
```
tailwind.config.js
```javascript
module.exports = {    
    ...
    plugins: [
        require('@tailwindcss/typography'),
        require('tailwindcss'),
        require('autoprefixer')
    ],
};

```
Is there something specific I need to do to load the plugins and utilities in a different order?

**Comment by RubenVanEldik** [comment]
This has already been discussed in #26 , I think.

**Comment by adamwathan** [comment]
Yep, check #26 for existing discussion and solutions 👍  Need to throw this in the docs probably.
