### ISSUE TITLE
How do you extend these values?

### ISSUE THREAD

**Issue by trovster** [tailwindcss/typography#4]
In my `tailwind.config.js` I am trying to override the colours using the `extend` property;

    extend: {
      typography: {
        h1: {
          color: '#fff'
        },
        ...
      },
    }

The colour is applied, but not the weight, size of line-height. The defaults are lost.

How can I override specific values?

**Comment by adamwathan** [comment]
This plugin is not built in a way that supports overriding it right now, still just a very early prototype that I am already completely rewriting. Better off copying the whole thing into your project and editing it directly until we actually tag a release we intend for people to use.

**Comment by trovster** [comment]
Thanks @adamwathan, I was afraid that'd be the case. Looking forward to the full release.
